repos:
  - repo: .
    rev: a6981f28492b9f48bbfacac2798d03982b0ff70f
    hooks:
      - id: find-trailing-comma
      - id: force-yaml-file-ext
      - id: poetry-check-lock
      - id: yamlfmt
        exclude: codecov\.yml$
