name: test
on:
  push:
    branches:
      - '*'
      - '**'
      - '!renovate/**'
      - '!chore/update-pre-commit'
  create:
    tags:
      - v*
  pull_request:
    branches:
      - '*'
      - '**'
jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [windows, ubuntu]
        python: ['3.6', '3.7', '3.8', '3.9']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - uses: Trim21/setup-poetry@dist/v1
      - uses: Trim21/install-poetry-project@dist/v1
      - name: test
        run: coverage run -m pytest
      - run: bash <(curl -s https://codecov.io/bash) -F py_${PYTHON//./}
        shell: bash
        env:
          PYTHON: ${{ matrix.python }}
